In [1]:
import pandas as pd

## reading data

In [2]:
df=pd.read_csv('data.csv')

In [3]:
df.head()

fever  bodypain  age  runnyNose  diffBreath  infectionProb
0  101.918784         0   67          1           0              0
1   98.172897         1   51          0           0              0
2   98.908470         0   49          0          -1              0
3  101.054983         0    3          1           1              1
4  100.077269         1   42          0           1              0

In [4]:
df.tail()

fever  bodypain  age  runnyNose  diffBreath  infectionProb
2683   98.974382         0  100          0           0              0
2684  101.294528         1   23          1           1              0
2685   99.465468         0   65          0          -1              1
2686  101.558067         0   72          1           1              1
2687  100.232426         0   56          1          -1              0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2688 entries, 0 to 2687
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fever          2688 non-null   float64
 1   bodypain       2688 non-null   int64  
 2   age            2688 non-null   int64  
 3   runnyNose      2688 non-null   int64  
 4   diffBreath     2688 non-null   int64  
 5   infectionProb  2688 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 126.1 KB


In [6]:
df['diffBreath'].value_counts()

 1    912
 0    898
-1    878
Name: diffBreath, dtype: int64

In [7]:
df.describe()


fever     bodypain          age    runnyNose   diffBreath  \
count  2688.000000  2688.000000  2688.000000  2688.000000  2688.000000   
mean    100.014841     0.490327    51.361607     0.497396     0.012649   
std       1.163703     0.499999    28.434115     0.500086     0.816095   
min      98.001244     0.000000     1.000000     0.000000    -1.000000   
25%      98.998002     0.000000    27.000000     0.000000    -1.000000   
50%     100.028119     0.000000    52.000000     0.000000     0.000000   
75%     101.029304     1.000000    76.000000     1.000000     1.000000   
max     101.999514     1.000000   100.000000     1.000000     1.000000   

       infectionProb  
count    2688.000000  
mean        0.485863  
std         0.499893  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

# train test splitting

In [8]:
import numpy as np


In [9]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled=np.random.permutation(len(data))
    test_set_size=int(len(data) * ratio)
    test_indices=shuffled[:test_set_size]
    train_indices=shuffled[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]
    
    

In [10]:
np.random.permutation(7)

array([0, 2, 6, 4, 1, 5, 3])

In [11]:
train,test=data_split(df,0.2)

In [12]:
train

fever  bodypain  age  runnyNose  diffBreath  infectionProb
208    98.074692         0   54          1          -1              0
610    99.360515         1   72          0           0              0
2004  100.460480         1   37          1          -1              0
1406  100.137490         0   56          1           1              1
1213   99.264395         0   68          0           0              0
...          ...       ...  ...        ...         ...            ...
1638  101.791358         0    1          0           0              0
1095   99.630768         1   38          0           0              1
1130  101.693085         0   53          0           0              0
1294  100.611131         1   67          1          -1              1
860    99.535464         1   17          0           0              1

[2151 rows x 6 columns]

In [13]:
test

fever  bodypain  age  runnyNose  diffBreath  infectionProb
1339   99.583787         1   17          1           1              0
2216  101.911818         0   91          1           0              0
368    99.485017         1    7          0           1              0
535    99.664866         0   26          1           1              0
2583   99.296215         1   32          1           1              0
...          ...       ...  ...        ...         ...            ...
1425   98.629941         0   61          1          -1              1
964    98.661945         0   45          1           1              0
1293   98.620674         0   67          1           0              0
1461  101.060458         1    8          0           1              0
353    99.129800         0   94          0           1              1

[537 rows x 6 columns]

In [14]:
X_train=train[['fever','bodypain','age','runnyNose','diffBreath']]

In [15]:
X_train.to_numpy()

array([[ 98.07469173,   0.        ,  54.        ,   1.        ,
         -1.        ],
       [ 99.36051467,   1.        ,  72.        ,   0.        ,
          0.        ],
       [100.4604795 ,   1.        ,  37.        ,   1.        ,
         -1.        ],
       ...,
       [101.6930849 ,   0.        ,  53.        ,   0.        ,
          0.        ],
       [100.6111314 ,   1.        ,  67.        ,   1.        ,
         -1.        ],
       [ 99.53546384,   1.        ,  17.        ,   0.        ,
          0.        ]])

In [16]:
X_test=test[['fever','bodypain','age','runnyNose','diffBreath']]

In [17]:
X_test.to_numpy()

array([[ 99.58378741,   1.        ,  17.        ,   1.        ,
          1.        ],
       [101.9118181 ,   0.        ,  91.        ,   1.        ,
          0.        ],
       [ 99.48501731,   1.        ,   7.        ,   0.        ,
          1.        ],
       ...,
       [ 98.62067359,   0.        ,  67.        ,   1.        ,
          0.        ],
       [101.0604578 ,   1.        ,   8.        ,   0.        ,
          1.        ],
       [ 99.12980011,   0.        ,  94.        ,   0.        ,
          1.        ]])

In [18]:
Y_train=train[['infectionProb']].to_numpy().reshape(2151,)
Y_test=test[['infectionProb']].to_numpy().reshape(537,)

In [19]:
Y_train

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

# logistic regression

In [20]:
from sklearn.linear_model import LogisticRegression


In [21]:
clf= LogisticRegression()
clf.fit(X_train,Y_train)

LogisticRegression()

In [22]:
input_features=[100,1,25,-1,1]
infprob=clf.predict_proba([input_features])

In [23]:
clf.predict([[100,1,25,-1,1]])

array([1], dtype=int64)

In [24]:
infprob=infprob[0][1]
infprob

0.5108388827493713